export const covers = {
  SarahStrong: {
    title: "Sarah Strong",
    date: new Date("2026-02-12"),
    number: "260",
    league: "College",
    team: ["UConn"],
    players: ["Sarah Strong"],
    photos: 6,
  },
  ScottieBarnesBrandonIngram: {
    title: "Scottie Barnes & Brandon Ingram",
    date: new Date("2026-02-11"),
    number: 260,
    league: "NBA",
    team: ["Toronto Raptors"],
    players: ["Scottie Barnes", "Brandon Ingram"],
    photos: 6,
  },
  ArizonaWildcats: {
    title: "Arizona Wildcats",
    date: new Date("2026-01-29"),
    number: "018",
    league: "College",
    team: ["Arizona Wildcats"],
    players: ["Jaden Bradley", "Koa Peat", "Brayden Burries"],
    photos: 6,
  },
  TyreseMaxeyVJEdgecombe: {
    title: "Tyrese Maxey & VJ Edgecombe",
    date: new Date("2026-01-28"),
    number: 260,
    league: "NBA",
    team: ["Philadelphia 76ers"],
    players: ["Tyrese Maxey", "VJ Edgecombe"],
    photos: 9,
  },
  IsaiahEvans: {
    title: "Isaiah Evans",
    date: new Date("2026-01-14"),
    number: "017",
    league: "College",
    team: ["Duke"],
    players: ["Isaiah Evans"],
    photos: 6,
  },
  JalenDuren: {
    title: "Jalen Duren",
    date: new Date("2026-01-13"),
    number: 260,
    league: "NBA",
    team: ["Detroit Pistons"],
    players: ["Jalen Duren"],
    photos: 7,
  },
  ElliotCadeauYaxelLendeborg: {
    title: "Elliot Cadeau & Yaxel Lendeborg",
    date: new Date("2025-12-11"),
    number: "015",
    league: "College",
    team: ["Michigan"],
    players: ["Elliot Cadeau", "Yaxel Lendeborg"],
    photos: 6,
  },
  SaniyahHall: {
    title: "Saniyah Hall",
    date: new Date("2025-11-21"),
    number: "007",
    league: "High School",
    team: ["SPIRE"],
    players: ["Saniyah Hall"],
    photos: 7,
  },
  CalebWilson: {
    title: "Caleb Wilson",
    date: new Date("2025-11-19"),
    number: "014",
    league: "College",
    team: ["North Carolina"],
    players: ["Caleb Wilson"],
    photos: 6,
  },
  JasonCroweJr: {
    title: "Jason Crowe Jr.",
    date: new Date("2025-11-17"),
    number: "006",
    league: "High School",
    team: ["Inglewood"],
    players: ["Jason Crowe Jr."],
    photos: 8,
  },
  LaurenSiennaBetts: {
    title: "Lauren & Sienna Betts",
    date: new Date("2025-11-05"),
    number: "012",
    league: "College",
    team: ["UCLA"],
    players: ["Sienna Betts", "Lauren Betts"],
    photos: 7,
  },
  AzziFudd: {
    title: "Azzi Fudd",
    date: new Date("2025-10-22"),
    number: "259",
    league: "College",
    team: ["UConn"],
    players: ["Azzi Fudd"],
    photos: 6,
  },
  AJDybantsa: {
    title: "AJ Dybantsa",
    date: new Date("2025-10-21"),
    number: "259",
    league: "College",
    team: ["BYU"],
    players: ["AJ Dybantsa"],
    photos: 7,
  },
  JalenWilliams: {
    title: "Jalen Williams",
    date: new Date("2025-09-17"),
    number: 258,
    league: "NBA",
    team: ["Oklahoma City Thunder"],
    players: ["Jalen Williams"],
    photos: 8,
  },
  CooperFlagg: {
    title: "Cooper Flagg",
    date: new Date("2025-08-26"),
    number: 258,
    league: "NBA",
    team: ["Dallas Mavericks"],
    players: ["Cooper Flagg"],
    photos: 7,
  },
  JaMorant: {
    title: "Ja Morant",
    date: new Date("2025-08-20"),
    league: "Other",
    team: ["Memphis Grizzlies"],
    players: ["Ja Morant"],
    photos: 4,
  },
  AusarThompsonAmenThompson: {
    title: "Ausar Thompson & Amen Thompson",
    date: new Date("2025-07-22"),
    number: 257,
    league: "NBA",
    team: ["Houston Rockets"],
    players: ["Amen Thompson", "Ausar Thompson"],
    photos: 10,
  },
  AliyahBoston: {
    title: "Aliyah Boston",
    date: new Date("2025-07-17"),
    number: "ASW",
    league: "WNBA",
    team: ["Indiana Fever"],
    players: ["Aliyah Boston"],
    photos: 4,
  },
  NapheesaCollier: {
    title: "Napheesa Collier",
    date: new Date("2025-06-30"),
    number: 257,
    league: "WNBA",
    team: ["Minnesota Lynx"],
    players: ["Napheesa Collier"],
    photos: 6,
  },
  CameronCaydenBoozer: {
    title: "Cameron & Cayden Boozer",
    date: new Date("2025-06-12"),
    number: "010",
    league: "College",
    team: ["Duke"],
    players: ["Cameron Boozer", "Cayden Boozer"],
    photos: 7,
  },
  NatashaCloud: {
    title: "Natasha Cloud",
    date: new Date("2025-05-27"),
    number: 256,
    league: "WNBA",
    team: ["New York Liberty"],
    players: ["Natasha Cloud"],
    photos: 7,
  },
  LosAngelesSparks: {
    title: "Los Angeles Sparks",
    date: new Date("2025-05-23"),
    number: 256,
    league: "WNBA",
    team: ["Los Angeles Sparks"],
    players: [
      "Kelsey Plum",
      "Dearica Hamby",
      "Cameron Brink",
      "Rickea Jackson",
    ],
    photos: 11,
  },
  CaitlinClark: {
    title: "Caitlin Clark",
    date: new Date("2025-05-19"),
    number: 256,
    league: "WNBA",
    team: ["Indiana Fever"],
    players: ["Caitlin Clark"],
    photos: 3,
  },
  PhoenixMercury: {
    title: "Phoenix Mercury",
    date: new Date("2025-05-12"),
    number: 256,
    league: "WNBA",
    team: ["Phoenix Mercury"],
    players: ["Kahleah Copper", "Satou Sabally", "Alyssa Thomas"],
    photos: 7,
  },
  CadeCunningham: {
    title: "Cade Cunningham",
    date: new Date("2025-04-09"),
    number: 255,
    league: "NBA",
    team: ["Detroit Pistons"],
    players: ["Cade Cunningham"],
    photos: 6,
  },
  DariusGarlandDonovanMitchell: {
    title: "Darius Garland & Donovan Mitchell",
    date: new Date("2025-03-24"),
    number: 255,
    league: "NBA",
    team: ["Cleveland Cavaliers"],
    players: ["Darius Garland", "Donovan Mitchell"],
    photos: 4,
  },
  JarenJacksonJr: {
    title: "Jaren Jackson Jr.",
    date: new Date("2025-03-20"),
    number: 255,
    league: "NBA",
    team: ["Memphis Grizzlies"],
    players: ["Jaren Jackson Jr."],
    photos: 8,
  },
  LSU: {
    title: "LSU",
    date: new Date("2025-02-28"),
    number: "005",
    league: "College",
    team: ["LSU"],
    players: ["Mikaylah Williams", "Flau’jae Johnson", "Aneesah Morrow"],
    photos: 6,
  },
  StJohnsRedStorm: {
    title: "St. John's Red Storm",
    date: new Date("2025-02-10"),
    number: "004",
    league: "College",
    team: ["St. John’s Red Storm"],
    players: ["RJ Luis Jr.", "Zuby Ejiofor", "Kadary Richmond", "Rick Pitino"],
    photos: 5,
  },
  KarlAnthonyTowns: {
    title: "Karl-Anthony Towns",
    date: new Date("2025-01-23"),
    number: 254,
    league: "NBA",
    team: ["New York Knicks"],
    players: ["Karl-Anthony Towns"],
    photos: 5,
  },
  ShaiGilgeousAlexander: {
    title: "Shai Gilgeous-Alexander",
    date: new Date("2025-02-14"),
    number: 254,
    league: "NBA",
    team: ["Oklahoma City Thunder"],
    players: ["Shai Gilgeous-Alexander"],
    photos: 4,
  },
  HoustonRockets: {
    title: "Houston Rockets",
    date: new Date("2025-02-05"),
    number: 254,
    league: "NBA",
    team: ["Houston Rockets"],
    players: [
      "Alperen Sengun",
      "Dillon Brooks",
      "Fred VanVleet",
      "Jalen Green",
    ],
    photos: 6,
  },
  IowaState: {
    title: "Iowa State",
    date: new Date("2025-01-14"),
    number: "002",
    league: "College",
    team: ["Iowa State"],
    players: ["Curtis Jones", "Keshon Gilber"],
    photos: 5,
  },
  AceBaileyDylanHarper: {
    title: "Ace Bailey & Dylan Harper",
    date: new Date("2024-10-16"),
    number: 253,
    league: "College",
    team: ["Rutgers"],
    players: ["Dylan Harper", "Ace Bailey"],
    photos: 6,
  },
  DamianLillard: {
    title: "Damian Lillard",
    date: new Date("2024-10-03"),
    number: 252,
    league: "NBA",
    team: ["Milwaukee Bucks"],
    players: ["Damian Lillard"],
    photos: 4,
  },
  DerrickWhiteJrueHoliday: {
    title: "Derrick White & Jrue Holiday",
    date: new Date("2024-09-30"),
    number: 252,
    league: "NBA",
    team: ["Boston Celtics"],
    players: ["Derrick White", "Jrue Holiday"],
    photos: 5,
  },
  AlyssaThomasDeWannaBonner: {
    title: "Alyssa Thomas & DeWanna Bonner",
    date: new Date("2024-07-18"),
    number: 251,
    league: "WNBA",
    team: ["Connecticut Sun"],
    players: ["Alyssa Thomas", "DeWanna Bonner"],
    photos: 4,
  },
  DawnStaley: {
    title: "Dawn Staley",
    date: new Date("2024-05-30"),
    number: 250,
    league: "College",
    team: ["South Carolina"],
    players: ["Dawn Staley"],
    photos: 4,
  },
  StephonCastleDonovanClingan: {
    title: "Stephon Castle & Donovan Clingan",
    date: new Date("2024-06-05"),
    number: 250,
    league: "College",
    team: ["UConn"],
    players: ["Stephon Castle", "Donovan Clingan"],
    photos: 6,
  },
  JimmyButler: {
    title: "Jimmy Butler",
    date: new Date("2024-04-15"),
    number: 249,
    league: "NBA",
    team: ["Miami Heat"],
    players: ["Jimmy Butler"],
    photos: 6,
  },
  NewYorkKnicks: {
    title: "New York Knicks",
    date: new Date("2024-04-10"),
    number: 249,
    league: "NBA",
    team: ["New York Knicks"],
    players: ["Jalen Brunson", "Josh Hart", "Donte DiVincenzo"],
    photos: 6,
  },
  CaitlinClark2: {
    title: "Caitlin Clark",
    date: new Date("2024-03-21"),
    number: 249,
    league: "College",
    team: ["Iowa"],
    players: ["Caitlin Clark"],
    photos: 8,
  },
  ChetHolmgren: {
    title: "Chet Holmgren",
    date: new Date("2024-02-12"),
    number: 248,
    league: "NBA",
    team: ["Oklahoma City Thunder"],
    players: ["Chet Holmgren"],
    photos: 4,
  },
  JujuWatkins: {
    title: "Juju Watkins",
    date: new Date("2024-02-05"),
    number: 248,
    league: "College",
    team: ["USC"],
    players: ["Juju Watkins"],
    photos: 9,
  },
  TyreseMaxey: {
    title: "Tyrese Maxey",
    date: new Date("2024-01-31"),
    number: 248,
    league: "NBA",
    team: ["Philadelphia 76ers"],
    players: ["Tyrese Maxey"],
    photos: 8,
  },
  CooperFlagg2: {
    title: "Cooper Flagg",
    date: new Date("2023-10-30"),
    number: 247,
    league: "College",
    team: ["Duke"],
    players: ["Cooper Flagg"],
    photos: 5,
  },
  OklahomaCityThunder: {
    title: "Oklahoma City Thunder",
    date: new Date("2023-10-23"),
    number: 247,
    league: "NBA",
    team: ["Oklahoma City Thunder"],
    players: [
      "Shai Gilgeous-Alexander",
      "Lu Dort",
      "Chet Holmgren",
      "Josh Giddey",
      "Jalen Williams",
    ],
    photos: 15,
  },
  PaulGeorge: {
    title: "Paul George",
    date: new Date("2023-09-27"),
    number: 246,
    league: "NBA",
    team: ["Los Angeles Clippers"],
    players: ["Paul George"],
    photos: 7,
  },
  NewYorkLiberty: {
    title: "New York Liberty",
    date: new Date("2023-09-12"),
    number: 246,
    league: "WNBA",
    team: ["New York Liberty"],
    players: [
      "Breanna Stewart",
      "Jonquel Jones",
      "Sabrina Ionescu",
      "Betnijah Laney",
      "Courtney Vandersloot",
    ],
    photos: 13,
  },
  SLAMKICKSExclusive: {
    title: "SLAMKICKS Exclusive",
    date: new Date("2023-08-28"),
    league: "Other",
    team: ["New Orleans Pelicans", "Boston Celtics", "Dallas Mavericks"],
    players: ["Zion Williamson", "Jayson Tatum", "Luka Dončić"],
    photos: 8,
  },
  PJTucker: {
    title: "P.J. Tucker",
    date: new Date("2023-08-31"),
    league: "Other",
    team: ["Philadelphia 76ers"],
    players: ["P.J. Tucker"],
    photos: 7,
  },
  BradleyBeal: {
    title: "Bradley Beal",
    date: new Date("2023-07-26"),
    number: 245,
    league: "NBA",
    team: ["Phoenix Suns"],
    players: ["Bradley Beal"],
    photos: 5,
  },
  TyreseHaliburton: {
    title: "Tyrese Haliburton",
    date: new Date("2023-07-20"),
    number: 245,
    league: "NBA",
    team: ["Indiana Pacers"],
    players: ["Tyrese Haliburton"],
    photos: 9,
  },
  PaoloBanchero: {
    title: "Paolo Banchero",
    date: new Date("2023-05-24"),
    number: 244,
    league: "NBA",
    team: ["Orlando Magic"],
    players: ["Paolo Banchero"],
    photos: 8,
  },
  RhyneHoward: {
    title: "Rhyne Howard",
    date: new Date("2023-05-19"),
    number: 244,
    league: "WNBA",
    team: ["Atlanta Dream"],
    players: ["Rhyne Howard"],
    photos: 6,
  },
  ScootHenderson: {
    title: "Scoot Henderson",
    date: new Date("2023-05-17"),
    number: 244,
    league: "NBA",
    team: ["Portland Trail Blazers"],
    players: ["Scoot Henderson"],
    photos: 10,
  },
  AngelReeseFlaujaeJohnson: {
    title: "Angel Reese & Flau'jae Johnson",
    date: new Date("2023-03-13"),
    number: 243,
    league: "College",
    team: ["LSU"],
    players: ["Angel Reese", "Flau'jae Johnson"],
    photos: 9,
  },
  JamesHarden: {
    title: "James Harden",
    date: new Date("2023-04-12"),
    number: 243,
    league: "NBA",
    team: ["Philadelphia 76ers"],
    players: ["James Harden"],
    photos: 7,
  },
  LauriMarkkanenJordanClarkson: {
    title: "Lauri Markkanen & Jordan Clarkson",
    date: new Date("2023-04-03"),
    number: 243,
    league: "NBA",
    team: ["Utah Jazz"],
    players: ["Lauri Markkanen", "Jordan Clarkson"],
    photos: 7,
  },
  JalenBrunson: {
    title: "Jalen Brunson",
    date: new Date("2023-03-30"),
    number: 243,
    league: "NBA",
    team: ["New York Knicks"],
    players: ["Jalen Brunson"],
    photos: 4,
  },
  NewOrleansPelicans: {
    title: "New Orleans Pelicans",
    date: new Date("2023-02-08"),
    number: 242,
    league: "NBA",
    team: ["New Orleans Pelicans"],
    players: ["Zion Williamson", "CJ McCollum", "Brandon Ingram"],
    photos: 4,
  },
  JaylenBrown: {
    title: "Jaylen Brown",
    date: new Date("2023-02-02"),
    number: 242,
    league: "NBA",
    team: ["Boston Celtics"],
    players: ["Jaylen Brown"],
    photos: 4,
  },
  DeAaronFoxDomantasSabonis: {
    title: "De'Aaron Fox & Domantas Sabonis",
    date: new Date("2023-01-26"),
    number: 242,
    league: "NBA",
    team: ["Sacramento Kings"],
    players: ["De'Aaron Fox", "Domantas Sabonis"],
    photos: 5,
  },
  TraeYoungDejounteMurray: {
    title: "Trae Young & Dejounte Murray",
    date: new Date("2022-12-13"),
    number: 242,
    league: "NBA",
    team: ["Atlanta Hawks"],
    players: ["Trae Young", "Dejounte Murray"],
    photos: 5,
  },
  JaysonTatum: {
    title: "Jayson Tatum",
    date: new Date("2022-12-08"),
    number: 241,
    league: "NBA",
    team: ["Boston Celtics"],
    players: ["Jayson Tatum"],
    photos: 5,
  },
  KawhiLeonardPaulGeorge: {
    title: "Kawhi Leonard & Paul George",
    date: new Date("2022-10-17"),
    number: 240,
    league: "NBA",
    team: ["Los Angeles Clippers"],
    players: ["Kawhi Leonard", "Paul George"],
    photos: 3,
  },
  VictorWembanyama: {
    title: "Victor Wembanyama",
    date: new Date("2022-10-03"),
    number: 240,
    league: "Europe",
    team: ["Metropolitans 92"],
    players: ["Victor Wembanyama"],
    photos: 6,
  },
  ScottieBarnes: {
    title: "Scottie Barnes",
    date: new Date("2022-07-29"),
    number: 239,
    league: "NBA",
    team: ["Toronto Raptors"],
    players: ["Scottie Barnes"],
    photos: 4,
  },
  CadeCunningham2: {
    title: "Cade Cunningham",
    date: new Date("2022-05-26"),
    number: 238,
    league: "NBA",
    team: ["Detroit Pistons"],
    players: ["Cade Cunningham"],
    photos: 5,
  },
  MemphisGrizzlies: {
    title: "Memphis Grizzlies",
    date: new Date("2022-04-15"),
    number: 238,
    league: "NBA",
    team: ["Memphis Grizzlies"],
    players: [
      "Ja Morant",
      "Desmond Bane",
      "Jaren Jackson Jr.",
      "Dillon Brooks",
    ],
    photos: 5,
  },
  SouthCarolinaGamecocks: {
    title: "South Carolina Gamecocks",
    date: new Date("2022-03-17"),
    number: 238,
    league: "College",
    team: ["South Carolina"],
    players: [
      "Dawn Staley",
      "Zia Cooke",
      "Destanni Henderson",
      "Aliyah Boston",
    ],
    photos: 5,
  },
  LaMeloBall: {
    title: "LaMelo Ball",
    date: new Date("2022-03-30"),
    number: 237,
    league: "NBA",
    team: ["Charlotte Hornets"],
    players: ["LaMelo Ball"],
    photos: 5,
  },
  DeMarDeRozanZachLaVine: {
    title: "DeMar DeRozan & Zach LaVine",
    date: new Date("2022-02-01"),
    number: 237,
    league: "NBA",
    team: ["Chicago Bulls"],
    players: ["DeMar DeRozan", "Zach LaVine"],
    photos: 3,
  },
  KahleahCopper: {
    title: "Kahleah Copper",
    date: new Date("2022-01-27"),
    number: 236,
    league: "WNBA",
    team: ["Chicago Sky"],
    players: ["Kahleah Copper"],
    photos: 5,
  },
  DonovanMitchell: {
    title: "Donovan Mitchell",
    date: new Date("2021-12-02"),
    number: 235,
    league: "NBA",
    team: ["Utah Jazz"],
    players: ["Donovan Mitchell"],
    photos: 5,
  },
  AzziFuddPaigeBueckers: {
    title: "Azzi Fudd & Paige Bueckers",
    date: new Date("2021-11-30"),
    number: 235,
    league: "College",
    team: ["UConn"],
    players: ["Azzi Fudd", "Paige Bueckers"],
    photos: 5,
  },
  CandaceParker: {
    title: "Candace Parker",
    date: new Date("2021-07-12"),
    number: 233,
    league: "WNBA",
    team: ["Chicago Sky"],
    players: ["Candace Parker"],
    photos: 4,
  },
  WNBARevolution: {
    title: "WNBA Revolution",
    date: new Date("2021-05-12"),
    number: 232,
    league: "WNBA",
    team: ["Phoenix Mercury", "Los Angeles Sparks", "Seattle Storm"],
    players: [
      "Skylar Diggins-Smith",
      "Nneka Ogwumike",
      "Sue Bird",
      "Diana Taurasi",
    ],
    photos: 5,
  },
  JamalMurray: {
    title: "Jamal Murray",
    date: new Date("2020-12-23"),
    number: 230,
    league: "NBA",
    team: ["Denver Nuggets"],
    players: ["Jamal Murray"],
    photos: 5,
  },
  ZionWilliamson: {
    title: "Zion Williamson",
    date: new Date("2020-08-06"),
    number: 228,
    league: "College",
    team: ["Duke"],
    players: ["Zion Williamson"],
    photos: 6,
  },
  JaMorant2: {
    title: "Ja Morant",
    date: new Date("2020-03-16"),
    number: 227,
    league: "NBA",
    team: ["Memphis Grizzlies"],
    players: ["Ja Morant"],
    photos: 5,
  },
  BostonCeltics: {
    title: "Boston Celtics",
    date: new Date("2020-01-30"),
    number: 226,
    league: "NBA",
    team: ["Boston Celtics"],
    players: [
      "Marcus Smart",
      "Jayson Tatum",
      "Jaylen Brown",
      "Kemba Walker",
      "Gordon Hayward",
    ],
    photos: 6,
  },
  MiamiHeat: {
    title: "Miami Heat",
    date: new Date("2019-12-03"),
    number: 225,
    league: "NBA",
    team: ["Miami Heat"],
    players: ["Jimmy Butler", "Bam Adebayo", "Tyler Herro"],
    photos: 5,
  },
  Goodfellas: {
    title: "Goodfellas",
    date: new Date("2019-10-17"),
    number: 224,
    league: "NBA",
    team: ["Minnesota Timberwolves", "Phoenix Suns", "Golden State Warriors"],
    players: ["Karl-Anthony Towns", "Devin Booker", "D’Angelo Russell"],
    photos: 5,
  },
  NewOrleansPelicans2: {
    title: "New Orleans Pelicans",
    date: new Date("2019-10-21"),
    number: 224,
    league: "NBA",
    team: ["New Orleans Pelicans"],
    players: [
      "Zion Williamson",
      "Lonzo Ball",
      "Brandon Ingram",
      "Jrue Holiday",
    ],
    photos: 7,
  },
  LizCambageAjaWilson: {
    title: "Liz Cambage & A’ja Wilson",
    date: new Date("2019-07-16"),
    number: 223,
    league: "WNBA",
    team: ["Las Vegas Aces"],
    players: ["Liz Cambage", "A’ja Wilson"],
    photos: 5,
  },
  LouWilliams: {
    title: "Lou Williams",
    date: new Date("2019-07-17"),
    number: 223,
    league: "NBA",
    team: ["Los Angeles Clippers"],
    players: ["Lou Williams"],
    photos: 4,
  },
  JaMorant3: {
    title: "Ja Morant",
    date: new Date("2019-05-14"),
    number: 222,
    league: "College",
    team: ["Murray State"],
    players: ["Ja Morant"],
    photos: 7,
  },
  ZionWilliamson2: {
    title: "Zion Williamson",
    date: new Date("2019-05-13"),
    number: 222,
    league: "College",
    team: ["Duke"],
    players: ["Zion Williamson"],
    photos: 4,
  },
  DwyaneWade: {
    title: "Dwyane Wade",
    date: new Date("2019-03-22"),
    number: 221,
    league: "NBA",
    team: ["Miami Heat"],
    players: ["Dwyane Wade"],
    photos: 4,
  },
  KembaWalker: {
    title: "Kemba Walker",
    date: new Date("2019-01-28"),
    number: 220,
    league: "NBA",
    team: ["Charlotte Hornets"],
    players: ["Kemba Walker"],
    photos: 5,
  },
  LeBronJames: {
    title: "LeBron James",
    date: new Date("2019-01-30"),
    number: 220,
    league: "NBA",
    team: ["Los Angeles Lakers"],
    players: ["LeBron James"],
    photos: 12,
  },
  StephenCurry: {
    title: "Stephen Curry",
    date: new Date("2018-12-03"),
    number: 219,
    league: "NBA",
    team: ["Golden State Warriors"],
    players: ["Stephen Curry"],
    photos: 8,
  },
  RJBarrett: {
    title: "RJ Barrett",
    date: new Date("2018-10-15"),
    number: 218,
    league: "College",
    team: ["Duke"],
    players: ["RJ Barrett"],
    photos: 5,
  },
  JaysonTatum2: {
    title: "Jayson Tatum",
    date: new Date("2018-10-11"),
    number: 218,
    league: "NBA",
    team: ["Boston Celtics"],
    players: ["Jayson Tatum"],
    photos: 8,
  },
}; // Главная константа
